@startuml 待售车辆管理流程图

start

:车辆入库;

if (车辆操作?)
  then (出库)
    :车辆出库;
    :更新车辆状态为已销售;
  else if (调拨)
    :车辆调拨;
    :更新车辆状态为调拨中;
    :调拨完成;
    :更新所在门店和车辆状态;
  else if (维修)
    :车辆维修;
    :更新车辆状态为维修中;
    :维修完成;
    :更新车辆状态为在库;
  else
    :库存查询;
    :库存分析;
  endif
endif

stop

@enduml