@startuml 门店管理流程图

start

:提交入驻申请;
:总部审核;

if (审核通过?)
  then (是)
    :门店入驻;
    :门店信息初始化;
    :开始运营;
    :门店评级;
    :门店监控;
    
    if (门店状态变更?)
      then (暂停营业)
        :暂停营业;
        if (恢复营业?)
          then (是)
            back to :开始运营;
          else (否)
            :门店退出;
          endif
      else if (退出)
        :门店退出;
      else
        back to :门店监控;
      endif
    endif
  else (否)
    :申请驳回;
  endif

stop

@enduml