@startuml 门店信息管理流程图

start

:门店登录系统;
:进入门店信息管理;

if (操作类型?)
  then (信息编辑)
    :修改门店基本信息;
    :保存信息;
  else if (人员管理)
    :添加/编辑/删除人员;
    :保存人员信息;
  else if (权限设置)
    :设置人员权限;
    :保存权限设置;
  else
    :查看门店信息;
  endif
endif

stop

@enduml