@startuml 门店线索及订单查看流程图

start

:门店登录系统;
:进入门店线索及订单查看;

if (查看类型?)
  then (线索查看)
    :查看线索列表;
    :筛选线索;
    :查看线索详情;
  else if (订单查看)
    :查看订单列表;
    :筛选订单;
    :查看订单详情;
  else
    :数据统计;
    :查看统计报表;
  endif
endif

stop

@enduml