@startuml
!define RECTANGLE class
!define CIRCLE ()
!define DIAMOND diamond
!define ARROW -->

' 商品管理流程
start
:管理员登录店端管理系统;
:进入商品管理模块;
diamond "选择操作类型" as OperationType {
  -> 商品信息维护;
  -> 仓储管理;
  -> 定价管理;
  -> 货架信息管理;
  -> 库存管理;
}

' 商品信息维护
if (商品信息维护) then (是)
  diamond "选择操作" as ProductOperation {
    -> 添加商品;
    -> 编辑商品;
    -> 删除商品;
  }
  
  if (添加商品) then (是)
    :填写商品基本信息;
    :上传商品图片;
    :设置商品分类;
    :保存商品信息;
  else (否)
    if (编辑商品) then (是)
      :选择要编辑的商品;
      :修改商品信息;
      :保存修改;
    else (否)
      if (删除商品) then (是)
        :选择要删除的商品;
        :确认删除;
        :系统删除商品;
      endif
    endif
  endif

' 仓储管理
elseif (仓储管理) then (是)
  diamond "选择操作" as StorageOperation {
    -> 商品入库;
    -> 商品出库;
    -> 库存盘点;
  }
  
  if (商品入库) then (是)
    :填写入库单;
    :选择商品;
    :输入入库数量;
    :确认入库;
    :系统更新库存;
  else (否)
    if (商品出库) then (是)
      :填写出库单;
      :选择商品;
      :输入出库数量;
      :确认出库;
      :系统更新库存;
    else (否)
      if (库存盘点) then (是)
        :选择盘点范围;
        :输入实际库存数量;
        :系统生成盘点报告;
        :调整库存差异;
      endif
    endif
  endif

' 定价管理
elseif (定价管理) then (是)
  :选择要定价的商品;
  :设置销售价格;
  :设置促销价格;
  :设置价格生效时间;
  :保存定价信息;

' 货架信息管理
elseif (货架信息管理) then (是)
  :选择商品;
  :设置货架位置;
  :设置陈列信息;
  :保存货架信息;

' 库存管理
elseif (库存管理) then (是)
  :查看商品库存状态;
  :设置库存预警值;
  :查看库存预警信息;
  :处理库存异常;
  :生成库存报表;

endif

:商品管理流程结束;
stop

@enduml