@startuml
' 核心业务流程图
' 贪吃蛇游戏核心业务流程

title 贪吃蛇游戏核心业务流程图

start
:游戏开始;
:初始化蛇的位置和方向;
:生成初始食物;
:设置游戏速度;

repeat
  :蛇自动向前移动;
  :检测键盘输入调整方向;
  if (是否碰撞边界?) then (是)
    :游戏结束;
    break
  endif
  if (是否碰撞自身?) then (是)
    :游戏结束;
    break
  endif
  if (是否吃到食物?) then (是)
    :增加分数;
    :增加蛇的长度;
    :生成新食物;
  else (否)
    :蛇继续移动;
  endif
  :更新游戏画面;
  :等待游戏速度时间间隔;
repeat while (游戏未结束)

:显示游戏结束界面;
:计算并更新最高分;
:点击重新开始;
back to 游戏开始

stop
@enduml