@startuml 客户信息管理流程

start
:进入客户管理;
:查看客户列表;
if (操作选择) then (新增客户)
  :填写客户信息;
  :保存客户信息;
  :查看客户列表;
elif (编辑客户) then
  :修改客户信息;
  :保存客户信息;
  :查看客户列表;
elif (查看客户详情) then
  :查看基本信息;
  :查看联系历史;
  :查看互动记录;
  :查看客户列表;
elif (删除客户) then
  :确认删除;
  :查看客户列表;
endif

stop

@enduml