@startuml 库存管理流程

start
:进入库存管理;
:查看库存列表;
if (操作选择) then (入库操作)
  :填写入库信息;
  :保存入库记录;
  :查看库存列表;
elif (出库操作) then
  :填写出库信息;
  :保存出库记录;
  :查看库存列表;
elif (查看库存详情) then
  :查看基本信息;
  :查看出入库历史;
  :查看库存列表;
elif (库存盘点) then
  :填写盘点信息;
  :保存盘点记录;
  :查看库存列表;
endif

stop

@enduml