@startuml 供应商管理流程

start
:进入供应商管理;
:查看供应商列表;
if (操作选择) then (新增供应商)
  :填写供应商信息;
  :保存供应商信息;
  :查看供应商列表;
elif (编辑供应商) then
  :修改供应商信息;
  :保存供应商信息;
  :查看供应商列表;
elif (查看供应商详情) then
  :查看基本信息;
  :查看合作历史;
  :查看评估记录;
  :查看供应商列表;
elif (删除供应商) then
  :确认删除;
  :查看供应商列表;
endif

stop

@enduml