@startuml 工单管理流程

start
:进入工单管理;
:查看工单列表;
if (操作选择) then (新增工单)
  :填写工单信息;
  :保存工单;
  :查看工单列表;
elif (编辑工单) then
  :修改工单信息;
  :保存工单;
  :查看工单列表;
elif (查看工单详情) then
  :查看基本信息;
  :查看处理历史;
  :查看工单列表;
elif (处理工单) then
  :更新工单状态;
  :添加处理记录;
  :查看工单列表;
endif

stop

@enduml