@startuml 商机管理流程

start
:进入商机管理;
:查看商机列表;
if (操作选择) then (新增商机)
  :填写商机信息;
  :保存商机;
  :查看商机列表;
elif (编辑商机) then
  :修改商机信息;
  :保存商机;
  :查看商机列表;
elif (查看商机详情) then
  :查看基本信息;
  :更新商机阶段;
  :查看相关活动;
  :查看商机列表;
elif (删除商机) then
  :确认删除;
  :查看商机列表;
endif

stop

@enduml