@startuml
'客户信息管理流程图

title 客户信息管理流程

start

:登录店端系统;
:进入客户信息管理页面;
:查看客户列表;

if (需要操作?) then (是)
  if (操作类型?) then (添加)
    :添加客户信息;
    :填写客户详情;
    :提交保存;
  else if (编辑)
    :选择客户;
    :编辑客户信息;
    :保存更改;
  else (删除)
    :选择客户;
    :确认删除;
    :删除客户信息;
  endif
else (否)
  if (需要查询?) then (是)
    :输入查询条件;
    :执行查询;
    :查看查询结果;
  else (否)
    :返回;
  endif
endif

stop

@enduml