@startuml
'车辆信息管理流程图

title 车辆信息管理流程

start

if (用户角色?) then (客户)
  :登录系统;
  :进入车辆管理页面;
  if (是否有车辆信息?) then (是)
    :查看车辆列表;
    if (需要编辑/删除?) then (是)
      :编辑/删除车辆信息;
      :保存更改;
    else (否)
      :返回;
    endif
  else (否)
    :添加车辆信息;
    :填写车辆详情;
    :提交保存;
  endif
else (门店管理员)
  :登录店端系统;
  :进入车辆信息管理页面;
  :查看车辆列表;
  if (需要操作?) then (是)
    if (操作类型?) then (添加)
      :添加车辆信息;
      :填写车辆详情;
      :提交保存;
    else if (编辑)
      :编辑车辆信息;
      :保存更改;
    else (删除)
      :删除车辆信息;
    endif
  else (否)
    :返回;
  endif
endif

stop

@enduml